### PR TITLE
tlf-assemble: using r2rtf 1.0.0

### PR DESCRIPTION
**Pull request by elong0527**
- start to use `assemble_rtf` and `assemble_docx` to combine RTF files.

### CODE REVIEW

**Comment by elong0527** [comment]
The CI/CD did not pass, because we need to release r2rtf 0.4.0

**Comment by nanxstats** [comment]
OK, we should wait for r2rtf's v0.4.0 release before we merge.

**Review by nanxstats — CHANGES_REQUESTED** [review]
Update `renv.lock` and rerun GitHub Actions after r2rtf 0.4.0 is available on CRAN.

**Comment by nanxstats** [comment]
r2rtf 1.0.0 is now released to CRAN - for renv to pick it up, we have to wait a bit for the binary to build and propagate...

**Comment by nanxstats** [comment]
Waiting for r2rtf and httpuv to be updated in Posit Public Package Manager as they are just updated today on CRAN, then rerun the workflow.

**Review by nanxstats — APPROVED** [review]
Now the workflow passes, I'm merging this PR. Thanks for this major improvement!

**Pull request merged**
